---
- name: removing the required software
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - httpd
    - php
    - php-mysql
    - php-cli
    - php-pdo
    - mariadb
    - mariadb-server
