cat 010_PeopleLoveAnsible.yml >> towerzeroboltons.yml
cat 011_InstallingAnsible.yml >> towerzeroboltons.yml
cat 101-AnsibleModules.yml >> towerzeroboltons.yml
cat 102-AnsibleInventory.yml >> towerzeroboltons.yml
cat 103-AdHocCommands.yml >> towerzeroboltons.yml
cat 104-FactsAndVars.yml >> towerzeroboltons.yml
cat 105-TasksInAPlay.yml >> towerzeroboltons.yml
cat 106-HandlerTasks.yml >> towerzeroboltons.yml
cat 107-AnatomyOfAPlaybook.yml >> towerzeroboltons.yml
cat 108-DoMore.yml >> towerzeroboltons.yml
cat 109-Vault.yml >> towerzeroboltons.yml
cat 110-Roles.yml >> towerzeroboltons.yml
cat 111-RoleDistribution.yml >> towerzeroboltons.yml
