- name: Assure our preferences files directory exists
  file:
    path: /var/lib/awx/projects/LimeLight_Labs
    state: directory
    owner: awx
    group: awx

- name: Insert the LimeLight_Labs project
  uri:
    url: https://localhost/api/v2/projects/
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "LimeLight Ansible Tower Labs",
          "description": "Pre-baked labs for the Ansible LimeLight Project",
          "local_path": "LimeLight_Labs",
          "scm_type": "",
          "scm_url": "",
          "scm_branch": "",
          "scm_clean": false,
          "scm_delete_on_update": false,
          "credential": null,
          "timeout": 0,
          "organization": 1,
          "scm_update_on_launch": false,
          "scm_update_cache_timeout": 0,
          "custom_virtualenv": null
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False

