---
- name: Assure our preferences files directory exists
  file:
    path: "{{ limelight_deck_basepath }}/deck-ansible/prefs/"
    state: directory

- name: deploy the PHP default preferences file template for the slide deck
  template:
    src: templates/deck-ansible_prefs_default.prefs.php
    dest: "{{ limelight_deck_basepath }}/deck-ansible/prefs/default.prefs.php"
    mode: 0644
    backup: yes

- name: synchronize html basics deck
  synchronize:
    src: files/deck-ansible/
    dest: "{{ limelight_deck_basepath }}/deck-ansible/"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=prefs/default.prefs.php"

- name: "selinux context recursively httpd_sys_rw_content_t {{ limelight_deck_basepath }}"
  sefcontext:
    target: "{{ limelight_deck_basepath }}(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: "restorecon -irv {{ limelight_deck_basepath }}"

