---
- name: TurnKeyDemo
  hosts: localhost
  gather_facts: no

  roles:
    - role: ec2-deploy-instance
      vars:
        temp_inventory: ec2towertemp
        user_srvname: "kev-tower-{{ user_event | replace (' ','') }}"
#	m5d.xlarge has 4cpu/16ram/150ssd/.23c
#	user_instype: m5d.xlarge
        user_instype: i3.large
        user_image: ami-0c170ccfc104032e3
        user_tags:
          Name: "{{ user_srvname }}"
          Event: "{{ user_event }}"
          Owner: "{{ user_realname }}"
          Contact: "{{ user_email }}"
          Application: "Ansible Tower for {{ user_event }}"

  tasks:
    - name: Set a variable for tower_host
      set_fact:
        tower_host: "{{ newec2machine }}"


- hosts: ec2towertemp
  become: yes
  vars:
    ansible_ssh_user: centos
    ansible_ssh_private_key_file: /root/.ssh/kev-ansible-kev.pem
    tower_user: kev
    tower_pass: kev
    tower_email: root@redhat.com

  roles:
    - role: tower-config
      vars:
        tower_host: newec2machine
#    - role: virtual-clients
    - role: shutdown-time
      vars:
        system_shutdown: 720
        # 720 = 12 hours, # 1440 min = 1 day, 2160 = 1.5 days, 2880 = 2 days

