- name: GET SOME STUFF
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    loop_count: 5
    loop_message: "You can set a message with the variable loop_message but you didn't.  This is just the default message, which is kind of boring.  Pass a value for loop_message and it will be much more fun."

  tasks:
  - name: Loop some stuff
    include_role:
      name: loop
      public: yes
    vars:
      loop_now: "{{'%03d'|format(item|int) }}"
    loop: "{{ range(1 | int, (loop_count+1 | int)) | list }}"


