---
- name: TurnKeyDemo
  hosts: localhost
  gather_facts: no

  vars:
    temp_inventory: ec2temp
    user_srvname: "kev-{{ user_event | replace (' ','') }}"
    user_instype: i3.large
    user_image: ami-a8d369c0
    user_tags:
      Name: "{{ user_srvname }}"
      Event: "{{ user_event }}"
      Owner: "{{ user_realname }}"
      Contact: "{{ user_email }}"
      Application: "TurnKeyDemo for {{ user_event }}"

  roles:
     - role: ec2-deploy-instance

- hosts: ec2temp
  become: yes
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: /root/.ssh/kev-ansible-kev.pem
      # 1440 min = 1 day, 2160 = 1.5 days, 2880 = 2 days
    tower_shutdown: 90
    dboverwrite: True
  roles:
    - role: wordpress-server
    - role: shutdown-time
      vars:
        system_shutdown: 30




