---
- name: TurnKeyDemo
  hosts: localhost
  gather_facts: no

  vars:
    tower_inventory: ec2towertemp

  roles:
     - role: ec2-deploy-instance
       vars:
         user_srvname: "kev-{{ user_event | replace (' ','') }}"
         user_instype: t2.medium
         user_image: ami-0c170ccfc104032e3
         user_secgrpid: sg-020ab9b6d8eb28daf
         user_tags:
           Name: "{{ user_srvname }}"
           Event: "{{ user_event }}"
           Owner: "{{ user_realname }}"
           Contact: "{{ user_email }}"
           Application: "TurnKeyDemo for {{ user_event }}"

- hosts: ec2towertemp
  become: yes
  vars:
    ansible_ssh_user: centos
    ansible_ssh_private_key_file: /root/.ssh/kev-ansible-kev.pem
    tower_user: kev
    tower_pass: kev
    tower_email: root@redhat.com
      # 1440 min = 1 day, 2160 = 1.5 days, 2880 = 2 days
    tower_shutdown: 90

  roles:
    - tower-config
