---
# tasks file for tower-insert-jobtemplate- name: make sure we are ready to go
  debug:
    msg: "We are inserting a job template with INV {{ new_inventory_id }}, PROJ {{ new_project_id }}, machine CRED {{ new_machine_credential_id }}, and vault CRED {{ new_vault_credential_id }}"

- name: Insert the new job template
  uri:
    url: "https://{{ tower_host }}/api/v2/job_templates/"
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "Loop Job Template",
          "description": "This is a dummy job template that deploys the loop role",
          "job_type": "run",
          "inventory": {{ jt_inventory_id }},
          "project": {{ jt_project_id }},
          "playbook": {{ jt_playbook_name }},
          "forks": 0,
          "limit": "",
          "verbosity": 0,
          "extra_vars": {{ jt_extra_vars }},
          "job_tags": "",
          "force_handlers": false,
          "skip_tags": "",
          "start_at_task": "",
          "timeout": 0,
          "use_fact_cache": false,
          "host_config_key": "",
          "ask_diff_mode_on_launch": false,
          "ask_variables_on_launch": false,
          "ask_limit_on_launch": false,
          "ask_tags_on_launch": false,
          "ask_skip_tags_on_launch": false,
          "ask_job_type_on_launch": false,
          "ask_verbosity_on_launch": false,
          "ask_inventory_on_launch": false,
          "ask_credential_on_launch": false,
          "survey_enabled": false,
          "become_enabled": true,
          "diff_mode": false,
          "allow_simultaneous": false,
          "custom_virtualenv": null,
          "job_slice_count": 1,
          "credential": {{ jt_mcred_id }},
          "vault_credential": {{ jt_vcred_id }}
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
