---

### INVENTORIES

- name: Get the default inventory ID
  uri:
    url: https://localhost/api/v2/inventories/?name=Demo%20Inventory
    validate_certs: no
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
  register: demo_inventory

- name: "DELETE https://localhost{{ demo_inventory.json.results[0].url }}"
  uri:
    url: "https://localhost{{ demo_inventory.json.results[0].url }}"
    validate_certs: no
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    force_basic_auth: yes
    status_code: 201
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
