---
- name: "Admin credentials - {{ tzero_user }} / {{ tzero_pass }}"
  raw: "tower-manage update_password --username {{ tzero_user }} --password {{ tzero_pass }}"
  failed_when: False
  ignore_errors: yes
  no_log: True
  changed_when: False

- name: "Create Superuser {{ tower_user }}"
  raw: "tower-manage createsuperuser --username {{ tower_user }} --email root@redhat.com --noinput"
  failed_when: False
  ignore_errors: yes
  no_log: True
  changed_when: False

- name: "User credentials - {{ tower_user }} / {{ tower_pass }}"
  raw: "tower-manage update_password --username {{ tower_user }} --password {{ tower_pass }}"
  failed_when: False
  ignore_errors: yes
  no_log: True
  changed_when: False

- name: Attach a license file
  uri:
    url: "https://localhost/api/v2/config/"
    validate_certs: no
    method: POST
    user: "{{ tzero_user }}"
    password: "{{ tzero_pass }}"
    body: "{% if ll_iamtowerzero %}{{ zero_license_file }}{% else %}{{ user_license_file }}{% endif %}"
    body_format: json
    force_basic_auth: yes
  changed_when: False

- name: tower_cli.cfg file
  template:
    src: templates/tower_cli.cfg
    dest: /root/.tower_cli.cfg
    owner: root
    group: root
    mode: '0600'

