---
- name: httpd conf listening on 9999 instead
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen 9999'
  register: httpdconf

- name: Restarting HTTPD
  service:
    name: httpd.service
    state: started
    enabled: yes
  when: httpdconf.changed

- name: httpd.conf serving up index.php as the default
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '^<Directory "/var/www">'
    line: '    DirectoryIndex index.php'

