---
- name: httpd.conf
  copy:
    src: templates/httpd.con.ll
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  register: httpdconf

- name: .htaccess
  copy:
    src: templates/_htaccess
    dest: /var/www/html/.htaccess
    owner: nobody
    group: nobody
    mode: 0644

- name: Restarting HTTPD
  service:
    name: httpd.service
    state: started
    enabled: yes
  when: httpdconf.changed
