---
- name: httpd.conf
  copy:
    src: templates/httpd.conf.ll
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
  register: httpdconf

- name: Restarting HTTPD
  service:
    name: httpd.service
    state: started
    enabled: yes
  when: httpdconf.changed

- name: .htaccess
  copy:
    src: templates/_htaccess
    dest: /var/www/html/.htaccess
    owner: nobody
    group: nobody
    mode: 0644

- name: api.php
  copy:
    src: templates/api.php
    dest: /var/www/html/api.php
    owner: nobody
    group: nobody
    mode: 0644

- name: phpMyAdmin link
  file:
    src: /usr/share/phpMyAdmin/
    dest: /var/www/html/pma
    owner: nobody
    group: nobody
    state: link
