---
- name: EPEL
  yum:
    name: epel-release
    state: present

- name: Software packages are present
  yum:
    name:
      - unzip
      - MySQL-python
      - policycoreutils-python
      - httpd
      - php
      - php-mysql
      - mariadb
      - mariadb-server
      - phpMyAdmin
      - nano
      - wget
    state: latest


