---

- name: "Check in as a Tower server... we are a {{ ll_application }} server"
  uri:
    url: "http://{{ tzero_ip }}:9999/api/addtower/{{ ll_userid }}/"
  when: ll_application == "Tower"

- name: Check URL DEBUG for a Tower server
  debug:
    msg: |
      http://{{ tzero_ip }}:9999/api/addtower/{{ ll_userid }}/
  when: ll_application == "Tower"


- name: "Check in as a Worker server... ec2_hostname = {{ ll_hostname }}"
  uri:
    url: "http://{{ tzero_ip }}:9999/api/addworker/{{ ll_userid }}/{{ ll_application }}/{{ ll_application}}-host{{ ll_sequence }}/ec2_hostname/{{ ll_hostname }}/"

- name: "Check in as a Worker server... ansible_host = {{ ll_myip }}"
  uri:
    url: "http://{{ tzero_ip }}:9999/api/addworker/{{ ll_userid }}/{{ ll_application }}/{{ ll_application}}-host{{ ll_sequence }}/ansible_host/{{ ll_myip }}/"

