---

### CREDENTIALS

- name: Get the default credential ID
  uri:
    url: https://localhost/api/v2/credentials/?name=Demo%20Credential
    validate_certs: no
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
  register: demo_credentials

- name: "DELETE https://localhost{{ demo_credentials.json.results[0].url }}"
  uri:
    url: "https://localhost{{ demo_credentials.json.results[0].url }}"
    validate_certs: no
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    force_basic_auth: yes
    status_code: 201
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
