---

### HOSTS


- name: DELETE default hosts item
  uri:
    url: https://localhost/api/v2/hosts/1/
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
  failed_when: False
  tags:
    - delete_tower_defaults

- name: DELETE default inventory item
  uri:
    url: https://localhost/api/v2/inventories/1/
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
  failed_when: False
  tags:
    - delete_tower_defaults


### CREDENTIALS


- name: DELETE default credentials
  uri:
    url: https://localhost/api/v2/credentials/1/
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
  failed_when: False
  tags:
    - delete_tower_defaults


### PROJECTS


- name: DELETE default project
  uri:
    url: https://localhost/api/v2/projects/4/
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
  failed_when: False
  tags:
    - delete_tower_defaults

- name: DELETE default job template
  uri:
    url: https://localhost/api/v2/job_templates/5/
    method: DELETE
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
  failed_when: False
  tags:
    - delete_tower_defaults
