---
#- name: check some debug stuff
#  debug:
#    msg: "{{ tower_host }} and {{ tower_user }} and {{ tower_pass }} seem to be set"


#- name: Add tower inventory source
#  tower_inventory_source:
#    tower_host: "{{ inventory_hostname }}"
#    tower_username: "{{ tower_user }}"
#    tower_password: "{{ tower_pass }}"
#    name: Inventory source
#    description: My Inventory source
#    inventory: My inventory
#    credential: Devstack_credential
#    source: openstack
#    update_on_launch: true
#    overwrite: true
#    source_vars: '{ private: false }'
#    state: present
#    tower_verify_ssl: false


- name: Insert the new inventory
  uri:
    url: https://localhost/api/v2/inventories/
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "Lab Instances",
          "description": "These are the instances populated automatically for you.",
          "organization": 1,
          "kind": "",
          "host_filter": null,
          "variables": "---\nansible_password: 1234\nother_var: GoKEV",
          "insights_credential": null
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
  register: new_inventory_id

- name: Get the new inventory ID
  uri:
    url: https://localhost/api/v2/inventories/?name=Lab%20Instances
    validate_certs: no
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
  register: inventory_out


- name: spit out inventory result
  debug:
    msg: "{{ inventory_out }}"

- name: spit out inventory ID specifically
  debug:
    msg: "{{ inventory_out.results }}"
