- name: Insert the root machine credential
  uri:
    url: https://localhost/api/v2/credentials/
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "root",
          "description": "Machine credential root user",
          "organization": 1,
          "credential_type": 1,
          "inputs": {
              "password": "password_goes_here",
              "username": "root"
          }
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
