---
# tasks file for GoKEV-lab-configtower

- include: tower_config.yml
- include: delete_defaults.yml
- include: insert_credentials.yml
- include: insert_project.yml
- include: insert_inventory.yml
- include: insert_jobtemplates.yml
