---
- name: Admin credentials for tower account
  raw: echo "from django.contrib.auth.models import User; User.objects.create_superuser('{{ tower_user }}', '{{ tower_email }}', '{{ tower_pass }}')" | tower-manage shell
  failed_when: False
  ignore_errors: yes
  no_log: True
  changed_when: False
  delegate_to: "{{ inventory_hostname }}"

- name: Attach a license file
  uri:
    url: "https://{{ inventory_hostname }}/api/v2/config/"
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body: "{{ license_file }}"
    body_format: json
    force_basic_auth: yes
  changed_when: False
