---
- name: EPEL
  yum:
    name: epel-release
    state: present

- name: PIP
  yum:
    name: python2-pip
    state: present

# takes longer than 30 seconds.  I'll comment it out unless it's necessary
#- name: Update All Packages
#  yum:
#    name: "*"
#    state: latest
