---
# tasks file for deploy-ec2-instance

- ec2:
    aws_access_key: "{{ user_awskey }}"
    aws_secret_key: "{{ user_awssec }}"
    key_name: "{{ user_sshkey }}"
    group_id: "{{ user_secgrpid }}"
    instance_type: "{{ user_instype }}"
    image: "{{ user_image }}"
    wait: yes
    wait_timeout: 600
    vpc_subnet_id: "{{ user_subnet }}"
    assign_public_ip: yes
    region: "{{ user_region }}"
    instance_tags: "{{ user_tags }}"
    count_tag:
      Name: "{{ user_srvname }}"
    exact_count: 1
    instance_initiated_shutdown_behavior: terminate
  register: newec2info
  delegate_to: localhost
  changed_when: False

- name: "Set a variable for newec2machine = {{ newec2info.tagged_instances[0].public_ip }}"
  set_fact:
     newec2machine: "{{ newec2info.tagged_instances[0].public_ip }}"

- name: "Wait 15 seconds and probe {{ newec2machine }} ssh for 30 seconds"
  wait_for:
    port: 22
    host: "{{ newec2machine }}"
    search_regex: OpenSSH
    delay: 15
    timeout: 30
  connection: local

- name: "add {{ newec2machine }} host to group {{ temp_inventory }}"
  add_host:
    name: "{{ newec2machine }}"
    groups: "{{ temp_inventory }}"
  changed_when: False

