---
# tasks file for deploy-ec2-instance

- ec2:
    aws_access_key: "{{ user_awskey }}"
    aws_secret_key: "{{ user_awssec }}"
    key_name: "{{ user_sshkey }}"
    group_id: "{{ user_secgrpid }}"
    instance_type: "{{ user_instype }}"
    image: "{{ user_image }}"
    wait: yes
    wait_timeout: 600
    vpc_subnet_id: "{{ user_subnet }}"
    assign_public_ip: yes
    region: "{{ user_region }}"
    instance_tags: "{{ user_tags }}"
    count_tag:
      Name: "{{ user_srvname }}"
    exact_count: 1
    instance_initiated_shutdown_behavior: terminate
  register: newec2info
  delegate_to: localhost
  changed_when: False

- name: Info about the EC2 instance
  debug:
    msg: "INFO {{ newec2info.tagged_instances[0] }}"
  ignore_errors: true

- name: Wait 10 seconds and then check port 22 for 300 seconds
  wait_for:
    port: 22
    host: "{{ newec2info.tagged_instances[0].public_ip }}"
    search_regex: OpenSSH
    delay: 10
  connection: local

- name: "add {{ newec2info.tagged_instances[0].public_ip }} host to group {{ tower_inventory }}"
  add_host:
    name: "{{ newec2info.tagged_instances[0].public_ip }}"
    groups: "{{ tower_inventory }}"
  changed_when: False
