---
- name: "Create a new database {{ wpdbname }}"
  mysql_db:
    name: "{{ wpdbname }}"
    state: present

- name: "Create the user {{ wpdbuser }} for {{ wpdbname }}.*:ALL"
  mysql_user:
    host: localhost
    name: "{{ wpdbuser }}"
    password: "{{ wpdbpass }}"
    priv: "{{ wpdbname }}.*:ALL"
    update_password: always
    state: present

