---
- set_fact:
    wpconfigfile: "{{ wpwebpath }}/wp-config.php"

- name: "Checking to see if {{ wpconfigfile }} already exists."
  stat:
    path: "{{ wpconfigfile }}"
  register: iswpcfg

- name: "Does {{ wpconfigfile }} web path exist"
  debug:
    msg: "{{ iswpcfg.stat.exists }}"

- name: "copy config template into {{ wpconfigfile }}"
  template:
    src: templates/wp-config.php
    dest: "{{ wpconfigfile }}"
    owner: apache
    group: apache
    mode: 0644
    backup: yes

- set_fact:
    myhostname: "{{ ansible_fqdn }}"

- name: Conditionally use inventory_hostname for myhostname if this is an EC2 instance
  set_fact:
    myhostname: "{{ inventory_hostname }}"
  when: ansible_product_version | regex_search('amazon')

- name: copy our wordpress template sql dumps
  template:
    src: templates/wordpress.sql
    dest: /tmp/wordpress.sql
    owner: root
    group: root
    mode: 0644
  when: iswpcfg.stat.exists == False or dboverwrite == True

- name: import wordpress.sql to our wordpress server
  raw: 'mysql {{ wpdbname }} < /tmp/wordpress.sql'
  when: iswpcfg.stat.exists == False or dboverwrite == True
  ignore_errors: yes

- name: copy graphics for our content
  copy:
    src: "templates/{{ item }}"
    dest: "{{ wpwebpath }}/wp-content/themes/twentyseventeen/assets/images/{{ item }}"
    owner: apache
    group: apache
    mode: 0644
  with_items:
    - automate_all_the_things.png
    - header_ansible.jpg
    - header_cats.jpg
    - cat-hack01.jpg
    - cat-hack02.jpg
    - cat-hack03.gif

- name: copy our custom logo to the site
  copy:
    src: "{{ wpwebpath }}/wp-content/themes/twentyseventeen/assets/images/header_ansible.jpg"
    dest: "{{ wpwebpath }}/wp-content/themes/twentyseventeen/assets/images/header.jpg"
    remote_src: yes
    owner: apache
    group: apache
    mode: 0644

- name: add a random string so our header graphic has to load every time
  template:
    src: templates/custom-header.php
    dest: "{{ wpwebpath }}/wp-content/themes/twentyseventeen/inc/custom-header.php"
    owner: apache
    group: apache
    mode: 0644

- name: "Remove wordpress.sql template database if it still exists"
  file:
    path: /tmp/wordpress.sql
    state: absent
